ALTER SYSTEM SET gs_amm_enabled TO 'on';
ALTER SYSTEM SET gs_amm_legacy_control_enabled TO 'on';
ALTER SYSTEM SET gs_amm_native_auto_mode TO 'off';
ALTER SYSTEM SET gs_amm_allocator_only_mode TO 'off';
ALTER SYSTEM SET gs_amm_feedback_only_mode TO 'off';
ALTER SYSTEM SET gs_amm_allocator_only_grant_mb TO '64';
ALTER SYSTEM SET gs_amm_feedback_bootstrap_grant_mb TO '64';
ALTER SYSTEM SET gs_amm_feedback_max_grant_mb TO '128';
ALTER SYSTEM SET gs_amm_feedback_initial_ap_slots TO '1';
ALTER SYSTEM SET gs_amm_feedback_max_ap_slots TO '2';
ALTER SYSTEM SET gs_amm_feedback_stable_windows TO '2';
ALTER SYSTEM SET gs_amm_native_ap_cost_threshold TO '0';
ALTER SYSTEM SET gs_amm_shared_buffers_min_mb TO '256';
ALTER SYSTEM SET gs_amm_dynamic_target_mb TO '256';
ALTER SYSTEM SET gs_amm_resize_batch_mb TO '64';
ALTER SYSTEM SET gs_amm_resize_rate_limit_mb TO '64';
ALTER SYSTEM SET gs_amm_resize_observe_window_ms TO '0';
ALTER SYSTEM SET gs_amm_resize_cooldown_ms TO '0';
ALTER SYSTEM SET gs_amm_tp_recovery_cooldown_ms TO '0';
ALTER SYSTEM SET enable_resource_track TO 'off';
SELECT pg_reload_conf();
SELECT gs_amm_set_dynamic_target_mb(256);
